# Generated by Django 2.2.1 on 2023-10-29 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=50)),
                ('schematic_name', models.CharField(max_length=100)),
                ('drawing_number', models.CharField(max_length=50)),
                ('name_ru', models.CharField(max_length=100)),
                ('name_cn', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('parent_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.Part')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=255, verbose_name='Наименование схемы')),
                ('schema_number', models.CharField(max_length=255, verbose_name='Номер схемы')),
                ('drawing_number', models.CharField(max_length=255, verbose_name='Чертежный номер')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название на русском')),
                ('name_cn', models.CharField(max_length=255, verbose_name='Название на китайском')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('description', models.TextField(verbose_name='Описание')),
                ('parent_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parts.Component')),
            ],
        ),
    ]
